name: Build
run-name: Build
on:
  push:
    tags:
      - 'v*.*'
  pull_request:
    branches: [ main ]
jobs:
  build_manual_update:
    name: Build FinalBeansStatsManualUpdate.zip
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.1.1
      - name: Restore Packages
        run: nuget restore FinalBeansStats.sln
      - name: Build
        run: msbuild /t:build /p:configuration=Release /p:platform="x64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FinalBeansStatsManualUpdate
          path: bin/**

  build:
    name: Build FinalBeansStats.zip
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.1.1
      - name: Restore Packages
        run: nuget restore FinalBeansStats.sln
      - name: Build
        run: msbuild /t:build /p:configuration=ReleaseUpdate /p:platform="x64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FinalBeansStats
          path: bin/**
